name: news2meme
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.3.29
  - certifi=2020.6.20
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - ffmpeg=4.3
  - fonttools=4.25.0
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - nltk=3.7
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.1
  - pillow=9.0.1
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytorch=1.11.0
  - pytz=2021.3
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - scipy=1.7.3
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.2
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.1
  - tqdm=4.63.0
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - pyyaml==6.0
